### ISSUE TITLE
Add a flag to specifie the download url

### ISSUE THREAD

**Issue by floriplum** [Draphar/redditrip#1]
Hi,

After playing a bit with it i noticed that while the `-f` flag is great to download sites not supported, it would probably make sense to add an option that would specifies what url i want to force.
So something like `--force-urls` that would set the top level domains you want to force.

Greetings
And thanks for the interesting tool.

**Comment by Draphar** [comment]
Agreed. I have already implemented `--exclude <DOMAIN>`, and the reverse was on my plan.
Furthermore a future version is going to support an external downloader that can handle unsupported sites, for example `youtube-dl` which can then handle the specifics of video downloading.

**Comment by Draphar** [comment]
The option to restrict downloading to specific domains is implemented now: c2d86ba6ca2d60d819c62028ede56213ef542aa9
